### ISSUE TITLE
Compilation fails on Linux

### ISSUE THREAD

**Issue by vshymanskyy** [Wiznet/WizFi310_arduino_library#8]
```
/data2/sketchbook/libraries/WizFi310/src/WizFi310Client.cpp:10:27: fatal error: utility/Debug.h: No such file or directory
 #include "utility/Debug.h"
```

**Comment by vshymanskyy** [comment]
I'm on linux, which has case-sensitive filesystem...

**Comment by vshymanskyy** [comment]
@kaizen8501 thanks! btw, probably you forgot to update the version in library json file, so it's not yet available in Arduino IDE.

**Comment by kaizen8501** [comment]
@vshymanskyy Thank you for your interest. I forgot to update version so I modified. You can use our library in Arduino IDE soon.
